name: Build and deploy Node.js app to Azure Web App - shopzone

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Change directory to server
        working-directory: ./server

      - name: npm install, build, and test
        working-directory: ./server
        run: |
          npm install

      - name: Zip artifact for deployment
        working-directory: ./server
        run: zip -r release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./server/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: d8782e7e-4fa9-48dd-b552-3f18b61a9d7b
          client-secret: Lb58Qvz4JcPMX6cVRZsMgr893m5BHBKFUdZVaDN
          tenant-id: c6417d2b-bcfe-436f-aab2-f4a6f483e788
          subscription-id: 7849e98b-4af6-4eaf-9c2e-d0e5054c8459
          auth-type: 'SERVICE_PRINCIPAL'

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'shopzone'
          package: .
