name: Build and deploy Node.js app to Azure Web App - shopzone

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Change directory to server
        working-directory: ./server
        run: echo "Changed directory to server"

      - name: Set environment variables
        run: |
          echo "MONGODBURL=${{ secrets.MONGODBURL }}" >> $GITHUB_ENV
          echo "SECKERT_ACCESS_TOKEN=${{ secrets.SECKERT_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "REFRESH_ACCESS_TOKEN=${{ secrets.REFRESH_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" >> $GITHUB_ENV
          echo "CONTAINER_NAME=${{ secrets.CONTAINER_NAME }}" >> $GITHUB_ENV

      - name: npm install, build, and test
        working-directory: ./server
        run: |
          npm install
          npm start

      - name: Zip artifact for deployment
        working-directory: ./server
        run: zip -r release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ./server/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'shopzone'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
        env:
          MONGODBURL: ${{ secrets.MONGODBURL }}
          SECKERT_ACCESS_TOKEN: ${{ secrets.SECKERT_ACCESS_TOKEN }}
          REFRESH_ACCESS_TOKEN: ${{ secrets.REFRESH_ACCESS_TOKEN }}
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
